### PR TITLE
Update MANIFEST.in

### PR DESCRIPTION
**Pull request by smitfrank**

### CODE REVIEW

**Comment by Martiusweb** [comment]
AFAIK, test/test_*.py files don't need to be specified in the MANIFEST.in file:

> anything that looks like a test script: test/test*.py (currently, the Distutils don’t do anything with test scripts except include them in source distributions, but in the future there will be a standard for testing Python module distributions)

https://docs.python.org/3/distutils/sourcedist.html

**Comment by smitfrank** [comment]
Thanks. I updated it.

**Comment by smitfrank** [comment]
Hi @Martiusweb, can you take another look and see if it's ok?

**Comment by Martiusweb** [comment]
Thanks

**Pull request merged**
