### PR TITLE
Add PYPI deploy to Travis CI

### PR DESCRIPTION
**Pull request by webknjaz**
Also:
* simplified test jobs and converted to matrix
* simplified bits of yaml

Action items:
* encrypt your password and replace placeholder via additional commit to this branch

Refs:
- #50
- https://docs.travis-ci.com/user/encryption-keys/
- https://github.com/blog/2247-improving-collaboration-with-forks

Bonus possibilities:
- it is possible to store version with git tags and include it into distribution automatically via [setuptools-scm](https://pypi.python.org/pypi/setuptools_scm), but I didn't add this since I don't know whether you want it. It's just one line of code in `setup.py` anyway :)

### CODE REVIEW

**Comment by webknjaz** [comment]
@Martiusweb how does this look to you?

**Comment by Martiusweb** [comment]
Thank you for the PR.
I think we should squash all the commits which doesn't change the actual execution: all but the one enabling caching and the one enabling the deployment to pypi.

two nits:
- I prefer to use 4 spaces tabulations to be consistent with the rest of the repository
- maybe reorder the content of the file a bit: language, python, cache, then script and env

I need a bit more time to review the ins and outs of the automatic deployment to pypi. I also prefer to avoid adding a dependency to setuptools-scm as it might cause problems to someone downloading the tarball of a revision from github, and add a dependency that we can probably avoid.

**Comment by webknjaz** [comment]
JFYI: you have complete write access to the PR branch ;)

**Comment by Martiusweb** [comment]
I'll do the changes and merge then, it's just that I don't like to edit myself without discussing with the author :)

**Comment by webknjaz** [comment]
Oh, sure. It just adds some latency.

As for me, I'd only squash two commits, since I like atomic changes + it helps to trace the mind flow of code author from git history in future.

Regarding indentation, I also prefer 4 spaces in code, but YAML is a config and it is a different story with different style. Also, having dense indents in YAML helps to keep highly nested structure within visible area. Trust me, we used to have monstrous Travis config at CherryPy :)

**Comment by Martiusweb** [comment]
It worked perfectly for source distributions, but bdist_wheel didn't work, I'll investigate later. Thanks!

**Pull request merged**
